default:
  image: $IMAGE

stages:
  - configure
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE=="parent_pipeline"

select tests:
  stage: configure
  script:
    - dunecontrol --opts=$DUNE_OPTS_FILE --current all
    - |
      pushd build-cmake
        python3 ../bin/testing/findtests.py -f affectedtests.json -t origin/master
      popd
  artifacts:
    paths:
      - build-cmake
    expire_in: 3 hours

build dumux:
  stage: build
  script:
    - |
      pushd build-cmake
        make clean
        python3 ../bin/testing/runselectedtests.py -c affectedtests.json -b
      popd
  artifacts:
    paths:
      - build-cmake
    expire_in: 3 hours
  needs:
    - job: select tests
      artifacts: true

test dumux:
  stage: test
  script:
    - |
      pushd build-cmake
        python3 ../bin/testing/runselectedtests.py -c affectedtests.json -t
      popd
  needs:
    - job: build dumux
      artifacts: true
  artifacts:
    reports:
      junit: junit/dumux-cmake.xml
